# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Bundle",
    "Identity",
    "IdentityToken",
    "Signer",
    "TrustedRoot",
    "Verifier",
    "py_sign",
    "py_verify",
]

@typing.final
class Bundle:
    r"""
    A Sigstore bundle containing a signature, verification material, and
    transparency log entries.
    
    Bundles are the primary artifact exchanged between signers and verifiers.
    They can be serialized to JSON (`.sigstore.json` files) and parsed back.
    
    Example::
    
        bundle = Bundle.from_json(open("artifact.sigstore.json").read())
        print(bundle.media_type)
    """
    @property
    def media_type(self) -> builtins.str:
        r"""
        The bundle media type string.
        
        For example:
        ``"application/vnd.dev.sigstore.bundle.v0.3+json"``
        """
    @classmethod
    def from_json(cls, data: builtins.str) -> Bundle:
        r"""
        Parse a Sigstore bundle from a JSON string or bytes.
        
        Raises :exc:`BundleError` if the input is not valid bundle JSON.
        """
    def to_json(self) -> builtins.str:
        r"""
        Serialize the bundle to a JSON string.
        
        Raises :exc:`BundleError` on serialization failure (extremely rare).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Identity:
    r"""
    Identity policy specifying the expected signer for verification.
    
    Pass an ``Identity`` to :meth:`Verifier.verify_artifact` or
    :meth:`Verifier.verify_dsse` to assert who signed the artifact.
    
    Args:
        identity: The expected signer identity. For email-based OIDC
            providers this is an email address (e.g.
            ``"user@example.com"``). For GitHub Actions this is a
            workflow URI (e.g.
            ``"https://github.com/org/repo/.github/workflows/ci.yml@refs/heads/main"``).
        issuer:   The expected OIDC issuer URL. Strongly recommended;
            if omitted any issuer is accepted.
    
    Example::
    
        policy = Identity(
            identity="https://github.com/org/repo/.github/workflows/release.yml@refs/heads/main",
            issuer="https://token.actions.githubusercontent.com",
        )
    """
    @property
    def identity(self) -> typing.Optional[builtins.str]:
        r"""
        The required identity string, if set.
        """
    @property
    def issuer(self) -> typing.Optional[builtins.str]:
        r"""
        The required issuer URL, if set.
        """
    def __new__(cls, identity: builtins.str, issuer: typing.Optional[builtins.str] = None) -> Identity: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class IdentityToken:
    r"""
    An OIDC identity token used to authenticate with Fulcio during signing.
    
    Obtain a token via :meth:`detect_ambient` (for CI environments like
    GitHub Actions) or :meth:`from_jwt` (if you already have a raw JWT).
    
    Example (GitHub Actions)::
    
        token = IdentityToken.detect_ambient()
        signer = Signer.production(token)
        bundle = signer.sign_artifact(open("artifact.bin", "rb").read())
    
    Example (raw JWT)::
    
        token = IdentityToken.from_jwt(os.environ["SIGSTORE_TOKEN"])
    """
    @property
    def issuer(self) -> builtins.str:
        r"""
        The OIDC issuer URL (e.g. ``"https://token.actions.githubusercontent.com"``).
        """
    @property
    def subject(self) -> builtins.str:
        r"""
        The token subject (user ID or workflow identifier).
        """
    @property
    def identity(self) -> builtins.str:
        r"""
        The signer identity string.
        
        Returns the email address if present in the token, otherwise the
        subject. This is the value matched against :class:`Identity`.
        """
    @property
    def is_expired(self) -> builtins.bool:
        r"""
        Whether the token is expired.
        """
    @classmethod
    def from_jwt(cls, token: builtins.str) -> IdentityToken:
        r"""
        Parse an OIDC identity token from a raw JWT string.
        
        Args:
            token: A JWT string in ``header.payload.signature`` format.
        
        Raises :exc:`IdentityTokenError` if the JWT is malformed.
        """
    @classmethod
    def detect_ambient(cls) -> IdentityToken:
        r"""
        Detect an ambient OIDC credential from the current environment.
        
        Checks for well-known CI/CD environment variables (GitHub Actions
        ``ACTIONS_ID_TOKEN_REQUEST_*``, GitLab CI, Buildkite, etc.).
        
        Raises :exc:`IdentityTokenError` if no ambient credential is available
        or if detection fails.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Signer:
    r"""
    Signs artifacts using the Sigstore infrastructure.
    
    Construct via :meth:`production` or :meth:`staging`, providing an
    :class:`IdentityToken`. The token is used to obtain a short-lived Fulcio
    signing certificate; the resulting :class:`Bundle` includes the
    signature, certificate, and a Rekor transparency log entry.
    
    Example::
    
        token = IdentityToken.detect_ambient()
        signer = Signer.production(token)
    
        # Sign raw artifact bytes:
        bundle = signer.sign_artifact(open("artifact.bin", "rb").read())
    
        # Sign an in-toto DSSE statement:
        bundle = signer.sign_dsse(statement_json_bytes,
                                  "application/vnd.in-toto+json")
    """
    @classmethod
    def production(cls, token: IdentityToken) -> Signer:
        r"""
        Create a signer using the Sigstore public-good infrastructure.
        
        Args:
            token: An :class:`IdentityToken` for authentication with Fulcio.
        
        Raises :exc:`IdentityTokenError` if the token is expired.
        """
    @classmethod
    def staging(cls, token: IdentityToken) -> Signer:
        r"""
        Create a signer using the Sigstore staging infrastructure.
        
        For testing only. Bundles produced with the staging signer cannot be
        verified against the production trusted root.
        
        Args:
            token: An :class:`IdentityToken` for authentication.
        
        Raises :exc:`IdentityTokenError` if the token is expired.
        """
    def sign_artifact(self, input: builtins.bytes) -> Bundle:
        r"""
        Sign raw artifact bytes and return a Sigstore bundle.
        
        Contacts Fulcio (for a signing certificate) and Rekor (to record the
        signature in the transparency log). Releases the GIL during network
        I/O.
        
        Args:
            input: The raw artifact bytes to sign.
        
        Returns:
            A :class:`Bundle` containing the signature and verification material.
        
        Raises :exc:`SigningError` on any failure.
        """
    def sign_dsse(self, payload: builtins.bytes, payload_type: builtins.str) -> Bundle:
        r"""
        Sign an in-toto DSSE statement and return a Sigstore bundle.
        
        The ``payload`` must be a valid JSON-serialized in-toto statement.
        ``payload_type`` should be ``"application/vnd.in-toto+json"``.
        
        Args:
            payload:      The raw statement bytes (JSON-encoded in-toto statement).
            payload_type: The DSSE payload type URI.
        
        Returns:
            A :class:`Bundle` containing the DSSE envelope and verification material.
        
        Raises :exc:`SigningError` on any failure.
        """

@typing.final
class TrustedRoot:
    r"""
    Trust anchors for Sigstore verification.
    
    The ``TrustedRoot`` contains all cryptographic material required to verify
    Sigstore bundles: Fulcio CA certificates, Rekor public keys, CT log keys,
    and TSA certificates.
    
    For most users, :meth:`production` or :meth:`github` is the right choice.
    
    Example::
    
        # Fetch latest trust material via TUF (recommended for production):
        root = TrustedRoot.production()
    
        # Use embedded GitHub Actions root (no network needed):
        root = TrustedRoot.github()
    
        # Load from a local file:
        root = TrustedRoot.from_file("/path/to/trusted_root.json")
    """
    @classmethod
    def production(cls) -> TrustedRoot:
        r"""
        Fetch the Sigstore public-good trusted root via TUF.
        
        Makes a network request to download and verify the latest trust
        material from Sigstore's TUF repository. This is the recommended
        method for production use.
        
        Raises :exc:`TrustedRootError` if the fetch or verification fails.
        """
    @classmethod
    def staging(cls) -> TrustedRoot:
        r"""
        Fetch the Sigstore staging trusted root via TUF.
        
        Use this for testing against the Sigstore staging infrastructure.
        Not for production use.
        
        Raises :exc:`TrustedRootError` if the fetch or verification fails.
        """
    @classmethod
    def github(cls) -> TrustedRoot:
        r"""
        Load the GitHub Actions trusted root (embedded, no network required).
        
        Use this when verifying GitHub artifact attestations. The embedded
        root is kept up to date with library releases.
        
        Raises :exc:`TrustedRootError` if the embedded data is invalid
        (should not happen in normal use).
        """
    @classmethod
    def from_json(cls, data: builtins.str) -> TrustedRoot:
        r"""
        Parse a trusted root from a JSON string.
        
        Raises :exc:`TrustedRootError` if the JSON is invalid.
        """
    @classmethod
    def from_file(cls, path: builtins.str) -> TrustedRoot:
        r"""
        Load a trusted root from a JSON file on disk.
        
        Args:
            path: Filesystem path to the trusted root JSON file.
        
        Raises :exc:`TrustedRootError` if the file cannot be read or parsed.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Verifier:
    r"""
    Verifies Sigstore bundles against a trusted root.
    
    Construct via one of the class methods, then call
    :meth:`verify_artifact` or :meth:`verify_dsse`.
    
    Example::
    
        verifier = Verifier.production()
        bundle = Bundle.from_json(open("artifact.sigstore.json").read())
        policy = Identity(identity="user@example.com",
                          issuer="https://accounts.google.com")
    
        verifier.verify_artifact(open("artifact.bin", "rb").read(), bundle, policy)
        # raises VerificationError on failure, returns None on success
    """
    @classmethod
    def production(cls) -> Verifier:
        r"""
        Create a verifier using the Sigstore public-good trusted root.
        
        Fetches the latest trust material via TUF. Makes a network request.
        
        Raises :exc:`TrustedRootError` if the TUF fetch fails.
        """
    @classmethod
    def staging(cls) -> Verifier:
        r"""
        Create a verifier using the Sigstore staging trusted root.
        
        Fetches the latest staging trust material via TUF. For testing only.
        
        Raises :exc:`TrustedRootError` if the TUF fetch fails.
        """
    @classmethod
    def github(cls) -> Verifier:
        r"""
        Create a verifier using the embedded GitHub Actions trusted root.
        
        No network request is made. Use this for verifying GitHub artifact
        attestations in offline or air-gapped environments.
        
        Raises :exc:`TrustedRootError` if the embedded root data is invalid.
        """
    @classmethod
    def from_root(cls, root: TrustedRoot) -> Verifier:
        r"""
        Create a verifier from a pre-loaded :class:`TrustedRoot`.
        
        Use this when you have already loaded or cached the trusted root and
        want to avoid a repeated network fetch.
        """
    def verify_artifact(self, input: builtins.bytes, bundle: Bundle, policy: Identity) -> None:
        r"""
        Verify a raw artifact against a Sigstore bundle.
        
        Returns ``None`` on success. Raises :exc:`VerificationError` if
        verification fails for any reason (invalid signature, identity
        mismatch, expired certificate, etc.).
        
        Args:
            input:   The raw artifact bytes to verify.
            bundle:  The :class:`Bundle` produced during signing.
            policy:  The :class:`Identity` asserting the expected signer.
        """
    def verify_dsse(self, artifact: builtins.bytes, bundle: Bundle, policy: Identity) -> tuple[builtins.str, builtins.bytes]:
        r"""
        Verify a DSSE envelope bundle against an artifact and return the payload.
        
        The ``artifact`` bytes are required because the in-toto statement inside
        the DSSE envelope must reference the artifact's SHA-256 digest as one of
        its subjects. This ensures the attestation is bound to the artifact.
        
        Returns a ``(payload_type, payload_bytes)`` tuple on success.
        Raises :exc:`VerificationError` if verification fails.
        
        Args:
            artifact: The raw artifact bytes whose digest is claimed by the
                      in-toto statement.
            bundle:   The DSSE :class:`Bundle` produced during signing.
            policy:   The :class:`Identity` asserting the expected signer.
        
        Returns:
            A ``(str, bytes)`` tuple of ``(payload_type, payload_bytes)``.
        """

def py_sign(input: builtins.bytes, token: typing.Union[IdentityToken, builtins.str, None] = None, *, staging: builtins.bool = False) -> Bundle:
    r"""
    One-shot artifact signing.
    
    A convenience wrapper that handles token detection and signer construction
    automatically. For multiple signing operations, prefer constructing a
    :class:`Signer` once and reusing it.
    
    Args:
        input:   The raw artifact bytes to sign.
        token:   An :class:`IdentityToken` or a raw JWT string. If ``None``,
                 ambient OIDC detection is attempted (suitable for CI).
        staging: If ``True``, use the Sigstore staging infrastructure instead
                 of production. Default: ``False``.
    
    Returns:
        A :class:`Bundle` containing the signature and verification material.
    
    Raises:
        :exc:`SigningError`:        If signing fails.
        :exc:`IdentityTokenError`:  If no token is provided and ambient
                                    detection fails, or if the token is expired.
    """

def py_verify(input: builtins.bytes, bundle: typing.Union[Bundle, builtins.str], identity: builtins.str, issuer: typing.Optional[builtins.str] = None, *, trusted_root: typing.Optional[TrustedRoot] = None) -> None:
    r"""
    One-shot artifact verification.
    
    A convenience wrapper around :class:`Verifier` that handles trust root
    loading automatically. For repeated verifications, prefer constructing a
    :class:`Verifier` once and reusing it.
    
    Args:
        input:        The raw artifact bytes to verify.
        bundle:       A :class:`Bundle` object or a JSON string.
        identity:     The expected signer identity string.
        issuer:       The expected OIDC issuer URL. Strongly recommended.
        trusted_root: Optional pre-loaded :class:`TrustedRoot`. If not
                      provided, the Sigstore public-good root is fetched via
                      TUF.
    
    Raises:
        :exc:`VerificationError`: If verification fails.
        :exc:`BundleError`:       If ``bundle`` is a string that cannot be parsed.
        :exc:`TrustedRootError`:  If the trusted root cannot be fetched.
    """
