"""
Hand-written stubs for exceptions defined in sigstore._internal.

These can't be auto-generated by pyo3-stub-gen because pyo3::create_exception!
uses a bare module identifier that doesn't support dotted paths. They are
defined here and re-exported by __init__.py.
"""

from builtins import BaseException

class SigstoreError(Exception):
    """Base exception for all py-sigstore errors."""
    ...

class VerificationError(SigstoreError):
    """Raised when artifact or bundle verification fails."""
    ...

class SigningError(SigstoreError):
    """Raised when artifact signing fails."""
    ...

class BundleError(SigstoreError):
    """Raised when a Sigstore bundle cannot be parsed or is structurally invalid."""
    ...

class TrustedRootError(SigstoreError):
    """Raised when a TrustedRoot cannot be loaded, fetched, or parsed."""
    ...

class IdentityTokenError(SigstoreError):
    """Raised when an OIDC identity token is invalid, expired, or cannot be detected."""
    ...
